-- No-op marker migration.
--
-- Original intent: ALTER DATABASE ... SET timezone = 'Asia/Kolkata'.
-- That requires the DB owner AND a literal database name (not the
-- current_database() function call), and parses differently across
-- PostgreSQL builds — failed in embedded-pg used for local dev,
-- blocking deploys with `&& pm2 restart` chains.
--
-- Timezone correctness is fully covered without it:
--   1. pool.on('connect') in src/config/database.js fires
--      SET TIME ZONE 'Asia/Kolkata' on every checked-out connection.
--   2. Every "today" SQL filter uses IST-explicit math:
--      (created_at AT TIME ZONE 'Asia/Kolkata')::date = ...
--   3. ecosystem.config.js sets TZ=Asia/Kolkata on the Node process.
--   4. server.js sets process.env.TZ before any require() runs.
--
-- This file exists only so the migration sequence number isn't skipped.
-- If you really want to ALTER DATABASE, do it manually as the DB owner:
--   ALTER DATABASE digitaladbird SET timezone TO 'Asia/Kolkata';

SELECT 1;
