import type { Metadata } from 'next';
import { LegalPage, type LegalSection } from '@/components/legal/LegalPage';

export const metadata: Metadata = { title: 'Privacy Policy', description: 'Digital AdBird privacy policy for websites, CRM services, and connected integrations.' };

const sections: LegalSection[] = [
  {
    title: '1. Information We Collect',
    children: [
      { title: 'Account Information', paragraphs: ['When you create or use an account, we may collect your name, email address, phone number, role, company name, login details, team details, and account preferences.'] },
      { title: 'CRM and Lead Data', paragraphs: ['When you use our CRM or lead management tools, we may process lead information such as lead name, phone number, email address, campaign details, assigned user, team, status, call status, stage, source, notes, follow-up information, and activity history.'] },
      { title: 'Communication and Activity Data', paragraphs: ['We may collect call logs, chat records, task history, notifications, workflow actions, login sessions, and usage activity inside the platform.'] },
      { title: 'Integration Data', paragraphs: ['When you connect third-party services such as Google, Meta, WhatsApp, or other platforms, we may process data needed to provide the integration. This may include account identifiers, access permissions, configuration settings, sync logs, webhook events, and related metadata.'] },
      { title: 'Technical Data', paragraphs: ['We may collect IP address, browser type, device type, operating system, pages visited, error logs, and security logs to maintain, secure, and improve our services.'] },
    ],
  },
  {
    title: '2. Google User Data and Google Sheets Integration',
    paragraphs: ['If you choose to connect your Google account, Digital AdBird may request access to Google services such as Google Sheets and Google Drive for the purpose of creating, selecting, reading, and updating spreadsheets used with our CRM.', 'We may access the following Google-related data only after you grant permission:'],
    bullets: ['Your Google account email address.', 'Spreadsheet file information such as spreadsheet name, spreadsheet ID, and available spreadsheet list.', 'Spreadsheet tabs, headers, and row data required for CRM lead synchronization.', 'Google OAuth tokens required to keep the integration connected.', 'To allow users to connect their own Google Sheets.', 'To create CRM spreadsheet tabs and required headers.', 'To sync authorized CRM leads into connected Google Sheets.', 'To read allowed sheet changes such as lead status, call status, stage, last contacted value, and notes.', 'To keep CRM and Google Sheets data synchronized based on user permissions.', 'To show sync status, sync logs, and connection status inside the CRM.'],
    children: [{ title: 'Google Data Commitments', paragraphs: ['We do not use Google user data for advertising. We do not sell Google user data. We do not share Google user data with unrelated third parties.', 'OAuth tokens are stored securely and are not shown to users, admins, or third parties. Users may disconnect their Google account from the CRM at any time.'] }],
  },
  { title: '3. How We Use Information', bullets: ['Provide, operate, and maintain our CRM and business tools.', 'Manage users, teams, leads, campaigns, reports, notifications, and integrations.', 'Sync data with connected services selected by the user.', 'Improve performance, security, and reliability.', 'Provide customer support.', 'Detect and prevent fraud, misuse, unauthorized access, and technical issues.', 'Comply with legal, contractual, and regulatory obligations.'] },
  { title: '4. Role-Based Access and Data Visibility', paragraphs: ['Digital AdBird CRM uses role-based access controls. Users can access only the data permitted by their role and assigned permissions.'], bullets: ['Admins may access company-level CRM data based on authorized business needs.', 'RMs may access their team-related data.', 'Members and partners may access only their assigned or permitted leads.', 'Personal Google Sheets sync is limited to the leads the connected user is authorized to view.'] },
  { title: '5. Data Sharing', paragraphs: ['We may share data only in the following cases:'], bullets: ['With service providers required to operate our platform, such as hosting, database, analytics, communication, and infrastructure providers.', 'With third-party platforms that you choose to connect, such as Google, Meta, WhatsApp, or other business tools.', "With your organization's authorized admins and team members based on role permissions.", 'When required by law, regulation, court order, or valid legal process.', 'To protect the rights, safety, and security of Digital AdBird, users, customers, or the public.', 'We do not sell your personal data.'] },
  { title: '6. Data Storage and Security', paragraphs: ['We use reasonable technical and organizational measures to protect your data from unauthorized access, loss, misuse, alteration, or disclosure.'], bullets: ['Encrypted storage for sensitive integration tokens.', 'Role-based access controls.', 'Secure authentication.', 'Server-side permission checks.', 'Activity logs and audit records.', 'Restricted admin access.', 'Secure deployment practices.', 'No system is completely secure, but we work to protect your data using appropriate safeguards.'] },
  { title: '7. Data Retention', paragraphs: ['We retain information for as long as necessary to provide our services, comply with legal obligations, resolve disputes, enforce agreements, maintain audit logs, and support business operations.', 'If a user disconnects a Google account, we may remove or disable stored OAuth tokens and stop future Google Sheets syncing. Existing CRM records may remain in the CRM according to business, legal, or operational requirements.'] },
  { title: '8. Your Choices and Rights', paragraphs: ['Depending on applicable law and your account permissions, you may request to:'], bullets: ['Access your personal information.', 'Correct inaccurate information.', 'Delete certain information.', 'Disconnect third-party integrations.', 'Revoke Google access.', 'Request information about how your data is used.', 'To revoke Google access directly, you may also visit your Google Account permissions page and remove Digital AdBird access.'] },
  { title: '9. Cookies and Tracking', paragraphs: ['Our website and platform may use cookies or similar technologies to maintain sessions, improve user experience, secure login, analyze usage, and remember preferences.', 'You may control cookies through your browser settings, but disabling cookies may affect platform functionality.'] },
  { title: "10. Children's Privacy", paragraphs: ['Our services are intended for business and professional use. We do not knowingly collect personal information from children under the age required by applicable law.'] },
  { title: '11. Third-Party Links and Services', paragraphs: ['Our services may include links or integrations with third-party websites and services. We are not responsible for the privacy practices of third-party services. Please review their privacy policies before using them.'] },
  { title: '12. Changes to This Privacy Policy', paragraphs: ['We may update this Privacy Policy from time to time. Updated versions will be posted on this page with a revised "Last updated" date.'] },
  { title: '13. Contact Us', paragraphs: ['For privacy-related questions, data requests, or support, contact us using the details below.'] },
];

export default function PrivacyPolicyPage() {
  return <LegalPage title="Privacy Policy" updated="June 22, 2026" intro={['Digital AdBird ("Digital AdBird", "we", "our", or "us") respects your privacy and is committed to protecting the personal information and business data you share with us.', 'This Privacy Policy explains how we collect, use, store, disclose, and protect information when you use our websites, CRM platform, marketing tools, automation services, lead management tools, Google Sheets integrations, WhatsApp/Meta integrations, and other services provided by Digital AdBird.', 'Our website is accessible at https://digitaladbird.com and our CRM platform may be accessible through subdomains such as https://www.crm.digitaladbird.com.']} sections={sections} />;
}
