import type { Metadata } from 'next';
import { LegalPage, type LegalSection } from '@/components/legal/LegalPage';

export const metadata: Metadata = { title: 'Terms and Conditions', description: 'Terms governing the use of Digital AdBird websites, CRM services, and integrations.' };

const sections: LegalSection[] = [
  {
    title: '1. Interpretation and Definitions',
    paragraphs: [
      '"Company", "we", "us", or "our" refers to Digital AdBird, 3rd Floor, 4/18 Manoj Yadav Building, Saraswati Puram, Khargapur, Gomti Nagar, Lucknow, Uttar Pradesh, India - 226010.',
      '"Service" refers to Digital AdBird websites, CRM platform, lead management tools, marketing tools, automation tools, reporting tools, Google Sheets integrations, Meta/WhatsApp integrations, and any other services provided by Digital AdBird.',
      '"Website" refers to https://digitaladbird.com and related subdomains such as https://www.crm.digitaladbird.com.',
      '"User", "you", or "your" means the person, company, organization, or other legal entity accessing or using the Service.',
      '"Account" means a user account created to access the Service.',
      '"CRM Data" means leads, customer details, campaign details, call logs, notes, statuses, stages, reports, assignments, notifications, and related business data processed through the Service.',
      '"Third-Party Services" means services provided by third parties, including but not limited to Google, Meta, WhatsApp, hosting providers, analytics providers, and communication providers.',
    ],
  },
  { title: '2. Use of the Service', paragraphs: ['You agree to use the Service only for lawful business purposes and in accordance with these Terms.', 'You must not:'], bullets: ['Use the Service for illegal, fraudulent, harmful, abusive, or unauthorized activities.', 'Access data you are not authorized to access.', 'Attempt to bypass security controls, role permissions, or system restrictions.', 'Upload or sync data that you do not have permission to process.', 'Interfere with the security, availability, or performance of the Service.', 'Use the Service to send spam, misleading communication, or unlawful marketing messages.'] },
  { title: '3. Accounts and Access', paragraphs: ['You are responsible for maintaining the confidentiality of your login credentials and for all activities under your account.', 'You must provide accurate account information and keep it updated.', 'Digital AdBird may suspend or restrict access if we believe an account is being misused, compromised, used unlawfully, or used in violation of these Terms.'] },
  { title: '4. Role-Based Permissions', paragraphs: ['The Service may include different user roles such as admin, RM, member, partner, or other roles.', 'Access to leads, reports, notifications, Google Sheets sync, and other features may depend on your role and permissions.', 'You must not attempt to access or export data outside your authorized scope.'] },
  { title: '5. Google Sheets Integration', paragraphs: ['The Service may allow users to connect their Google account and sync authorized CRM data with Google Sheets.', 'By connecting Google Sheets, you authorize Digital AdBird to access and update spreadsheets for CRM-related purposes such as:'], bullets: ['Creating or connecting CRM spreadsheets.', 'Creating required tabs and headers.', 'Syncing authorized lead data.', 'Updating lead status, stage, call status, last contacted fields, and notes.', 'Reading allowed sheet changes for CRM synchronization.'], children: [{ title: 'User Responsibilities', paragraphs: ['Users are responsible for ensuring that connected Google Sheets are used appropriately and not shared with unauthorized persons.', 'Digital AdBird is not responsible for unauthorized access caused by users sharing their Google Sheets outside the platform.', 'Users may disconnect Google integration at any time from the CRM or from their Google Account permissions.'] }] },
  { title: '6. CRM and Lead Data', paragraphs: ['You are responsible for the accuracy, legality, and authorization of CRM data entered, imported, uploaded, synced, or processed through the Service.', 'You confirm that you have the necessary rights and permissions to process any lead, customer, campaign, or business data through Digital AdBird.', 'Digital AdBird may process CRM data only to provide, maintain, secure, and improve the Service.'] },
  { title: '7. Third-Party Integrations', paragraphs: ['The Service may integrate with third-party platforms such as Google, Meta, WhatsApp, or other services.', 'Your use of third-party integrations is also subject to the terms and policies of those third-party providers.', 'Digital AdBird is not responsible for outages, API changes, permission changes, quota limits, rejected approvals, or restrictions imposed by third-party platforms.'] },
  { title: '8. Data Sync and Accuracy', paragraphs: ['The Service may sync data between CRM and connected tools such as Google Sheets.', 'Although we work to keep synced data accurate, sync delays, API limits, user edits, conflicts, permission issues, and third-party errors may affect data accuracy.', 'The CRM database should be treated as the primary system of record unless otherwise specified by your organization.'] },
  { title: '9. Fees and Payment', paragraphs: ['Some services may be free, paid, subscription-based, or custom-priced based on business requirements.', 'Payment terms, billing cycles, refunds, and cancellation terms may be provided separately in proposals, invoices, agreements, or plan details.'] },
  { title: '10. Intellectual Property', paragraphs: ['All software, design, branding, content, platform features, workflows, and technology provided by Digital AdBird are owned by Digital AdBird or its licensors, unless otherwise stated.', 'You may not copy, resell, reverse engineer, modify, distribute, or exploit the Service without written permission.'] },
  { title: '11. Confidentiality', paragraphs: ['Users may access sensitive business, lead, campaign, or customer data through the Service. You agree to keep such information confidential and use it only for authorized business purposes.'] },
  { title: '12. Limitation of Liability', paragraphs: ['To the maximum extent permitted by law, Digital AdBird shall not be liable for indirect, incidental, special, consequential, or punitive damages, including loss of profits, loss of data, business interruption, or third-party service failures.', 'The Service is provided on an "as is" and "as available" basis, unless otherwise agreed in writing.'] },
  { title: '13. No Guarantee of Third-Party Approval', paragraphs: ['Digital AdBird does not guarantee approval from Google, Meta, WhatsApp, or any third-party platform. Access to third-party APIs may depend on verification, permissions, account status, compliance, and policies of those platforms.'] },
  { title: '14. Suspension and Termination', paragraphs: ['We may suspend or terminate access if you violate these Terms, misuse the Service, fail to pay applicable fees, compromise security, or use the Service unlawfully.', 'You may stop using the Service at any time. Certain data may be retained as required for legal, operational, audit, or security purposes.'] },
  { title: '15. Privacy', paragraphs: ['Your use of the Service is also governed by our Privacy Policy. Please review it to understand how we collect, use, store, and protect data.', 'Privacy Policy URL: https://digitaladbird.com/privacy-policy'] },
  { title: '16. Changes to These Terms', paragraphs: ['We may update these Terms from time to time. Updated Terms will be posted on this page with a revised "Last updated" date.', 'Continued use of the Service after changes means you accept the updated Terms.'] },
  { title: '17. Governing Law', paragraphs: ['These Terms shall be governed by and interpreted in accordance with the laws of India.'] },
  { title: '18. Contact Us', paragraphs: ['For questions about these Terms, contact us using the details below.'] },
];

export default function TermsPage() {
  return <LegalPage title="Terms and Conditions" updated="June 22, 2026" intro={['Please read these Terms and Conditions carefully before using Digital AdBird websites, CRM platform, marketing tools, automation services, integrations, and related services.', 'By accessing or using our services, you agree to be bound by these Terms. If you do not agree with any part of these Terms, you should not use our services.']} sections={sections} />;
}
