'use client';
import { useEffect, useState, FormEvent } from 'react';
import toast from 'react-hot-toast';
import { Modal } from '@/components/ui/Modal';
import { Button } from '@/components/ui/Button';
import { Input, Select } from '@/components/ui/Input';
import { useCreateUser, useUpdateUser } from '@/hooks/useUsers';
import type { User, Role } from '@/types';

interface Props {
  open: boolean;
  onClose: () => void;
  initial?: User | null;
  rms: User[];
}

const ROLE_OPTS: { value: Role; label: string }[] = [
  { value: 'member', label: 'Member' },
  { value: 'rm', label: 'Relationship Manager' },
  { value: 'super_admin', label: 'Super Admin' },
];

function userFormError(error: unknown) {
  const data = (error as { response?: { data?: { code?: string; message?: string; error?: { message?: string } | string } } })?.response?.data;
  if (data?.code === 'CP_ID_NOT_EDITABLE') return 'CP ID is system generated and cannot be edited.';
  if (data?.code === 'PARTNER_ROLE_DEPRECATED') return 'Partner users are now managed as Members.';
  return typeof data?.error === 'string' ? data.error : data?.message || data?.error?.message;
}

export function UserFormModal({ open, onClose, initial, rms }: Props) {
  const editing = !!initial;
  const create = useCreateUser();
  const update = useUpdateUser();
  const busy = create.isPending || update.isPending;

  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  const [role, setRole] = useState<Role>('member');
  const [team, setTeam] = useState('');
  const [reportTo, setReportTo] = useState('');
  const [cap, setCap] = useState<number | ''>('');
  const [weight, setWeight] = useState<number | ''>(1);
  const [sendWelcomeEmail, setSendWelcomeEmail] = useState(true);

  const activeRms = rms.filter(u => u.role === 'rm' && u.status === 'active');

  useEffect(() => {
    if (!open) return;
    setName(initial?.full_name ?? '');
    setEmail(initial?.email ?? '');
    setPhone(initial?.phone ?? '');
    setRole(initial?.role === 'partner' ? 'member' : (initial?.role ?? 'member'));
    setTeam(initial?.team_name ?? '');
    setReportTo(initial?.report_to_id ?? '');
    setCap(initial?.daily_lead_cap ?? '');
    setWeight(initial?.distribution_weight ?? 1);
    setSendWelcomeEmail(true);
  }, [open, initial]);

  function handleSubmit(e: FormEvent) {
    e.preventDefault();
    if (!name.trim() || !email.trim() || !phone.trim()) {
      toast.error('Name, email and phone are required');
      return;
    }
    if (role === 'rm' && !team.trim()) {
      toast.error('Team name is required for RM');
      return;
    }
    if (role === 'member' && !reportTo) {
      toast.error('Reporting RM is required for member');
      return;
    }

    const payload = {
      full_name: name.trim(),
      email: email.trim(),
      phone: phone.trim(),
      role,
      team_name: role === 'rm' ? team.trim() : null,
      report_to_id: role === 'member' ? reportTo : null,
      daily_lead_cap: role === 'member' && cap !== '' ? Number(cap) : null,
      distribution_weight: role === 'member' && weight !== '' ? Number(weight) : 1,
      ...(!editing ? { sendWelcomeEmail } : {}),
    };

    if (editing && initial) {
      update.mutate({ id: initial.id, ...payload }, {
        onSuccess: () => { toast.success('User updated'); onClose(); },
        onError: (err: unknown) => toast.error(userFormError(err) || 'Update failed'),
      });
      return;
    }

    create.mutate(payload, {
      onSuccess: (created) => {
        toast.success(`User created${created.cp_id ? ` (${created.cp_id})` : ''}`);
        if (created.emailWarning) toast.error(created.emailWarning);
        onClose();
      },
      onError: (err: unknown) => toast.error(userFormError(err) || 'Create failed'),
    });
  }

  return (
    <Modal
      open={open}
      onClose={onClose}
      title={editing ? 'Edit user' : 'Add team member'}
      description="CP ID is generated by the system. The user can set a password through the secure onboarding email."
      size="lg"
      footer={(
        <>
          <Button variant="ghost" onClick={onClose} disabled={busy}>Cancel</Button>
          <Button onClick={handleSubmit} loading={busy}>{editing ? 'Save changes' : 'Create user'}</Button>
        </>
      )}
    >
      <form onSubmit={handleSubmit} className="grid grid-cols-1 gap-3 sm:grid-cols-2">
        <Input label="Full name" value={name} onChange={(e) => setName(e.target.value)} required />
        <Input label="Email" value={email} onChange={(e) => setEmail(e.target.value)} type="email" required />
        <Input label="Mobile (E.164)" value={phone} onChange={(e) => setPhone(e.target.value)}
          placeholder="+9198xxxxxxxx" hint="Include country code." required />
        {editing && (
          <Input label="CP ID" value={initial?.cp_id || 'System generated'} disabled
            className="font-mono" hint="CP ID is system generated and cannot be edited." />
        )}
        <Select label="Role" value={role} options={ROLE_OPTS} onChange={(e) => setRole(e.target.value as Role)} />
        <Input label="Team name" value={team} onChange={(e) => setTeam(e.target.value)}
          placeholder="e.g. Sales North" required={role === 'rm'} disabled={role === 'member'}
          hint={role === 'member' ? 'Members inherit team name from their reporting RM.' : undefined} />
        <Select label="Reporting RM" value={reportTo} placeholder="Select RM"
          options={activeRms.map(u => ({ value: u.id, label: `${u.full_name} - ${u.team_name || 'RM Team'}` }))}
          onChange={(e) => setReportTo(e.target.value)}
          disabled={role !== 'member'} required={role === 'member'}
          hint="Members must report to an active RM." />
        {role === 'member' && (
          <>
            <Input label="Daily lead cap" type="number" min={0}
              value={cap} onChange={(e) => setCap(e.target.value === '' ? '' : Number(e.target.value))}
              hint="Leave blank for default." />
            <Input label="Distribution weight" type="number" min={0} step="0.1"
              value={weight} onChange={(e) => setWeight(e.target.value === '' ? '' : Number(e.target.value))}
              hint="Used by the weighted distribution strategy." />
          </>
        )}
        {!editing && (
          <label className="flex items-center gap-2 text-sm text-slate-700 sm:col-span-2">
            <input type="checkbox" checked={sendWelcomeEmail} onChange={(e) => setSendWelcomeEmail(e.target.checked)}
              className="h-4 w-4 rounded border-slate-300" />
            Send onboarding email with password setup link
          </label>
        )}
      </form>
    </Modal>
  );
}
